version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  ruby-app:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    container_name: ruby_app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_app
    depends_on:
      - ruby-app
    volumes:
      - .:/usr/src/app

  # dotnet-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dotnet
  #   container_name: dotnet_app
  #   depends_on:
  #     - ruby-app
  #   volumes:
  #     - .:/usr/src/app
